feat: add an aggregated velocity statistics view
hasadna/open-bus-stride-db pull request #24
Opened 2024-12-23 18:09 UTC by NoamGaash

2024-12-24 07:35 UTC, OriHoch commented
I tried to run this query manually for a single day 

by adding WHERE date >= '2024-12-01' and date < '2024-12-02'

* to the HourlyAverages query - it takes 10 seconds and returns ~20,000 rows
* to the external query - it was running for more then 5 minutes so I stopped it

extrapolating to all the data we have - which currently is ~2 years the total number of rows will be 20,000 * 730 = 14,600,000

because it's a materialized view which stores all its rows and taking into account the indices, this will add significant size to the DB. Also, the load on the DB for running the materialized view refresh needs to be taken into account, we will need to run it periodically.

I think because the basic query takes 10 seconds per day, and assuming it won't run very often it's worth to just run the query itself, or maybe add a non-materizlied view.

2024-12-24 07:36 UTC, OriHoch requested changes
^

2024-12-24 07:59 UTC, NoamGaash commented
Thank you!
Ideally, I'd like to have some cache mechanism, because I want to expose an API endpoint to get a heatmap of velocity statistics, that I will call to from the frontent.
When considering 14 million rows, each row contains 7 values (8 bytes each I guess?) is about 56 bytes per row * 14,600,000 ~= 900MB. I can see how that's a lot.
The front-end will cache the responses, but it's still computationally heavy operation.
I'll read about non materialized views.
Thank you very much for the fast and educative feedback :pray:

2025-01-17 17:52 UTC, NoamGaash commented
Hi @OriHoch ! I came out with this proposal to implement some kind of cache mechanism.

the last used column will store the last time a specific date was calculated. It will be used to remove old entries from the DB.

I made an implementation for the API and tested it locally
https://github.com/hasadna/open-bus-stride-api/pull/44

2025-01-18 10:46 UTC, OriHoch commented
1. Currently the API is strictly for SELECT and I want to keep it that way as introducing updates/inserts into it introduces a lot of complexity and risk I want to keep out
2. Caching mechanisms I would prefer not to implement on the DB as that also introduces risks and scale problems, if you want caching we can add a Redis server but I prefer if we can avoid it
3. The idea of adding a new table and populating it is good, but the way to do it is via the ETL system, you can add a task that runs daily, iterates over all the dates for which all the source data exists and for which no data is in the new table and inserts their data to this table. Most of the tasks in the [open_bus_stride_etl](https://github.com/hasadna/open-bus-stride-etl/blob/main/open_bus_stride_etl) do something like this. I would name this table a more generic name maybe something like `siri_vehicle_locations_daily_stats` so in the future we can add other statistics to this table

2025-01-19 09:55 UTC, NoamGaash commented
Got it, thanks.
That's a pretty CPU intensive query, and I'm not sure we want to populate the entire table. It would be quite heavy (in storage).
We do have caching mechanism in the client side, but it's per browsing context.
The options I see here are:
1. Add an external cache (Redis)
2. Re-calculate the query every time (should we add a rate-limit or something?)
3. Add in-memory cache ([lru cache for example](https://internet-israel.com/%D7%A4%D7%99%D7%AA%D7%95%D7%97-%D7%90%D7%99%D7%A0%D7%98%D7%A8%D7%A0%D7%98/%D7%91%D7%A0%D7%99%D7%99%D7%AA-%D7%90%D7%AA%D7%A8%D7%99-%D7%90%D7%99%D7%A0%D7%98%D7%A8%D7%A0%D7%98-%D7%9C%D7%9E%D7%A4%D7%AA%D7%97%D7%99%D7%9D/%D7%9C%D7%90-%D7%9C%D7%A8%D7%95%D7%A5-%D7%9C-db-%D7%91%D7%9B%D7%9C-%D7%A4%D7%A2%D7%9D-%D7%A9%D7%A6%D7%A8%D7%99%D7%9A-cache/))
4. populate huge table

What do you think?

2025-01-19 09:59 UTC, OriHoch commented
4. populate huge table with an ETL process

2025-01-19 10:11 UTC, NoamGaash commented
@OriHoch didn't we said that 900MB is too much storage?

2025-01-19 10:30 UTC, OriHoch commented
I think it's OK, it's the least worse option

2025-01-25 18:22 UTC, closed without merging